#-------------------------------------------------
#
# Project created by QtCreator 2016-10-01T08:23:59
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets network

TARGET = gcom
TEMPLATE = app


SOURCES += main.cpp\
    modules/uas_message/uas_message_tcp_framer.cpp \
    modules/uas_message/request_message.cpp \
    modules/uas_message/system_info_message.cpp \
    modules/uas_message/command_message.cpp \
    modules/uas_message/response_message.cpp \
    gcom_controller.cpp \
    modules/mavlink_relay/mavlink_relay_tcp.cpp \
    modules/goose_census/goose_census.cpp \


HEADERS  += \
    modules/uas_message/uas_message.hpp \
    modules/mavlink_relay/mavlink_relay_tcp.hpp \
    modules/uas_message/request_message.hpp \
    modules/uas_message/system_info_message.hpp \
    modules/uas_message/command_message.hpp \
    modules/uas_message/response_message.hpp \
    gcom_controller.hpp \
    Mavlink/ardupilotmega/ardupilotmega.h \
    Mavlink/ardupilotmega/mavlink.h \
    Mavlink/ardupilotmega/mavlink_msg_ahrs.h \
    Mavlink/ardupilotmega/mavlink_msg_ahrs2.h \
    Mavlink/ardupilotmega/mavlink_msg_ahrs3.h \
    Mavlink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    Mavlink/ardupilotmega/mavlink_msg_ap_adc.h \
    Mavlink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    Mavlink/ardupilotmega/mavlink_msg_battery2.h \
    Mavlink/ardupilotmega/mavlink_msg_camera_feedback.h \
    Mavlink/ardupilotmega/mavlink_msg_camera_status.h \
    Mavlink/ardupilotmega/mavlink_msg_compassmot_status.h \
    Mavlink/ardupilotmega/mavlink_msg_data16.h \
    Mavlink/ardupilotmega/mavlink_msg_data32.h \
    Mavlink/ardupilotmega/mavlink_msg_data64.h \
    Mavlink/ardupilotmega/mavlink_msg_data96.h \
    Mavlink/ardupilotmega/mavlink_msg_digicam_configure.h \
    Mavlink/ardupilotmega/mavlink_msg_digicam_control.h \
    Mavlink/ardupilotmega/mavlink_msg_ekf_status_report.h \
    Mavlink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    Mavlink/ardupilotmega/mavlink_msg_fence_point.h \
    Mavlink/ardupilotmega/mavlink_msg_fence_status.h \
    Mavlink/ardupilotmega/mavlink_msg_gimbal_control.h \
    Mavlink/ardupilotmega/mavlink_msg_gimbal_report.h \
    Mavlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_get_request.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_get_response.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_set_request.h \
    Mavlink/ardupilotmega/mavlink_msg_gopro_set_response.h \
    Mavlink/ardupilotmega/mavlink_msg_hwstatus.h \
    Mavlink/ardupilotmega/mavlink_msg_led_control.h \
    Mavlink/ardupilotmega/mavlink_msg_limits_status.h \
    Mavlink/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    Mavlink/ardupilotmega/mavlink_msg_mag_cal_report.h \
    Mavlink/ardupilotmega/mavlink_msg_meminfo.h \
    Mavlink/ardupilotmega/mavlink_msg_mount_configure.h \
    Mavlink/ardupilotmega/mavlink_msg_mount_control.h \
    Mavlink/ardupilotmega/mavlink_msg_mount_status.h \
    Mavlink/ardupilotmega/mavlink_msg_pid_tuning.h \
    Mavlink/ardupilotmega/mavlink_msg_radio.h \
    Mavlink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    Mavlink/ardupilotmega/mavlink_msg_rally_point.h \
    Mavlink/ardupilotmega/mavlink_msg_rangefinder.h \
    Mavlink/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    Mavlink/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    Mavlink/ardupilotmega/mavlink_msg_rpm.h \
    Mavlink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    Mavlink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    Mavlink/ardupilotmega/mavlink_msg_simstate.h \
    Mavlink/ardupilotmega/mavlink_msg_wind.h \
    Mavlink/ardupilotmega/testsuite.h \
    Mavlink/ardupilotmega/version.h \
    Mavlink/ASLUAV/ASLUAV.h \
    Mavlink/ASLUAV/mavlink.h \
    Mavlink/ASLUAV/mavlink_msg_asl_obctrl.h \
    Mavlink/ASLUAV/mavlink_msg_aslctrl_data.h \
    Mavlink/ASLUAV/mavlink_msg_aslctrl_debug.h \
    Mavlink/ASLUAV/mavlink_msg_asluav_status.h \
    Mavlink/ASLUAV/mavlink_msg_ekf_ext.h \
    Mavlink/ASLUAV/mavlink_msg_fw_soaring_data.h \
    Mavlink/ASLUAV/mavlink_msg_sens_atmos.h \
    Mavlink/ASLUAV/mavlink_msg_sens_batmon.h \
    Mavlink/ASLUAV/mavlink_msg_sens_mppt.h \
    Mavlink/ASLUAV/mavlink_msg_sens_power.h \
    Mavlink/ASLUAV/mavlink_msg_sens_power_board.h \
    Mavlink/ASLUAV/mavlink_msg_sensorpod_status.h \
    Mavlink/ASLUAV/testsuite.h \
    Mavlink/ASLUAV/version.h \
    Mavlink/autoquad/autoquad.h \
    Mavlink/autoquad/mavlink.h \
    Mavlink/autoquad/mavlink_msg_aq_esc_telemetry.h \
    Mavlink/autoquad/mavlink_msg_aq_telemetry_f.h \
    Mavlink/autoquad/testsuite.h \
    Mavlink/autoquad/version.h \
    Mavlink/common/common.h \
    Mavlink/common/mavlink.h \
    Mavlink/common/mavlink_msg_actuator_control_target.h \
    Mavlink/common/mavlink_msg_adsb_vehicle.h \
    Mavlink/common/mavlink_msg_altitude.h \
    Mavlink/common/mavlink_msg_att_pos_mocap.h \
    Mavlink/common/mavlink_msg_attitude.h \
    Mavlink/common/mavlink_msg_attitude_quaternion.h \
    Mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    Mavlink/common/mavlink_msg_attitude_target.h \
    Mavlink/common/mavlink_msg_auth_key.h \
    Mavlink/common/mavlink_msg_autopilot_version.h \
    Mavlink/common/mavlink_msg_battery_status.h \
    Mavlink/common/mavlink_msg_button_change.h \
    Mavlink/common/mavlink_msg_camera_trigger.h \
    Mavlink/common/mavlink_msg_change_operator_control.h \
    Mavlink/common/mavlink_msg_change_operator_control_ack.h \
    Mavlink/common/mavlink_msg_collision.h \
    Mavlink/common/mavlink_msg_command_ack.h \
    Mavlink/common/mavlink_msg_command_int.h \
    Mavlink/common/mavlink_msg_command_long.h \
    Mavlink/common/mavlink_msg_control_system_state.h \
    Mavlink/common/mavlink_msg_data_stream.h \
    Mavlink/common/mavlink_msg_data_transmission_handshake.h \
    Mavlink/common/mavlink_msg_debug.h \
    Mavlink/common/mavlink_msg_debug_vect.h \
    Mavlink/common/mavlink_msg_distance_sensor.h \
    Mavlink/common/mavlink_msg_encapsulated_data.h \
    Mavlink/common/mavlink_msg_estimator_status.h \
    Mavlink/common/mavlink_msg_extended_sys_state.h \
    Mavlink/common/mavlink_msg_file_transfer_protocol.h \
    Mavlink/common/mavlink_msg_follow_target.h \
    Mavlink/common/mavlink_msg_global_position_int.h \
    Mavlink/common/mavlink_msg_global_position_int_cov.h \
    Mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    Mavlink/common/mavlink_msg_gps2_raw.h \
    Mavlink/common/mavlink_msg_gps2_rtk.h \
    Mavlink/common/mavlink_msg_gps_global_origin.h \
    Mavlink/common/mavlink_msg_gps_inject_data.h \
    Mavlink/common/mavlink_msg_gps_input.h \
    Mavlink/common/mavlink_msg_gps_raw_int.h \
    Mavlink/common/mavlink_msg_gps_rtcm_data.h \
    Mavlink/common/mavlink_msg_gps_rtk.h \
    Mavlink/common/mavlink_msg_gps_status.h \
    Mavlink/common/mavlink_msg_heartbeat.h \
    Mavlink/common/mavlink_msg_highres_imu.h \
    Mavlink/common/mavlink_msg_hil_actuator_controls.h \
    Mavlink/common/mavlink_msg_hil_controls.h \
    Mavlink/common/mavlink_msg_hil_gps.h \
    Mavlink/common/mavlink_msg_hil_optical_flow.h \
    Mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    Mavlink/common/mavlink_msg_hil_sensor.h \
    Mavlink/common/mavlink_msg_hil_state.h \
    Mavlink/common/mavlink_msg_hil_state_quaternion.h \
    Mavlink/common/mavlink_msg_home_position.h \
    Mavlink/common/mavlink_msg_landing_target.h \
    Mavlink/common/mavlink_msg_local_position_ned.h \
    Mavlink/common/mavlink_msg_local_position_ned_cov.h \
    Mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    Mavlink/common/mavlink_msg_log_data.h \
    Mavlink/common/mavlink_msg_log_entry.h \
    Mavlink/common/mavlink_msg_log_erase.h \
    Mavlink/common/mavlink_msg_log_request_data.h \
    Mavlink/common/mavlink_msg_log_request_end.h \
    Mavlink/common/mavlink_msg_log_request_list.h \
    Mavlink/common/mavlink_msg_manual_control.h \
    Mavlink/common/mavlink_msg_manual_setpoint.h \
    Mavlink/common/mavlink_msg_memory_vect.h \
    Mavlink/common/mavlink_msg_message_interval.h \
    Mavlink/common/mavlink_msg_mission_ack.h \
    Mavlink/common/mavlink_msg_mission_clear_all.h \
    Mavlink/common/mavlink_msg_mission_count.h \
    Mavlink/common/mavlink_msg_mission_current.h \
    Mavlink/common/mavlink_msg_mission_item.h \
    Mavlink/common/mavlink_msg_mission_item_int.h \
    Mavlink/common/mavlink_msg_mission_item_reached.h \
    Mavlink/common/mavlink_msg_mission_request.h \
    Mavlink/common/mavlink_msg_mission_request_int.h \
    Mavlink/common/mavlink_msg_mission_request_list.h \
    Mavlink/common/mavlink_msg_mission_request_partial_list.h \
    Mavlink/common/mavlink_msg_mission_set_current.h \
    Mavlink/common/mavlink_msg_mission_write_partial_list.h \
    Mavlink/common/mavlink_msg_named_value_float.h \
    Mavlink/common/mavlink_msg_named_value_int.h \
    Mavlink/common/mavlink_msg_nav_controller_output.h \
    Mavlink/common/mavlink_msg_optical_flow.h \
    Mavlink/common/mavlink_msg_optical_flow_rad.h \
    Mavlink/common/mavlink_msg_param_map_rc.h \
    Mavlink/common/mavlink_msg_param_request_list.h \
    Mavlink/common/mavlink_msg_param_request_read.h \
    Mavlink/common/mavlink_msg_param_set.h \
    Mavlink/common/mavlink_msg_param_value.h \
    Mavlink/common/mavlink_msg_ping.h \
    Mavlink/common/mavlink_msg_play_tune.h \
    Mavlink/common/mavlink_msg_position_target_global_int.h \
    Mavlink/common/mavlink_msg_position_target_local_ned.h \
    Mavlink/common/mavlink_msg_power_status.h \
    Mavlink/common/mavlink_msg_radio_status.h \
    Mavlink/common/mavlink_msg_raw_imu.h \
    Mavlink/common/mavlink_msg_raw_pressure.h \
    Mavlink/common/mavlink_msg_rc_channels.h \
    Mavlink/common/mavlink_msg_rc_channels_override.h \
    Mavlink/common/mavlink_msg_rc_channels_raw.h \
    Mavlink/common/mavlink_msg_rc_channels_scaled.h \
    Mavlink/common/mavlink_msg_request_data_stream.h \
    Mavlink/common/mavlink_msg_resource_request.h \
    Mavlink/common/mavlink_msg_safety_allowed_area.h \
    Mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    Mavlink/common/mavlink_msg_scaled_imu.h \
    Mavlink/common/mavlink_msg_scaled_imu2.h \
    Mavlink/common/mavlink_msg_scaled_imu3.h \
    Mavlink/common/mavlink_msg_scaled_pressure.h \
    Mavlink/common/mavlink_msg_scaled_pressure2.h \
    Mavlink/common/mavlink_msg_scaled_pressure3.h \
    Mavlink/common/mavlink_msg_serial_control.h \
    Mavlink/common/mavlink_msg_servo_output_raw.h \
    Mavlink/common/mavlink_msg_set_actuator_control_target.h \
    Mavlink/common/mavlink_msg_set_attitude_target.h \
    Mavlink/common/mavlink_msg_set_gps_global_origin.h \
    Mavlink/common/mavlink_msg_set_home_position.h \
    Mavlink/common/mavlink_msg_set_mode.h \
    Mavlink/common/mavlink_msg_set_position_target_global_int.h \
    Mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    Mavlink/common/mavlink_msg_setup_signing.h \
    Mavlink/common/mavlink_msg_sim_state.h \
    Mavlink/common/mavlink_msg_statustext.h \
    Mavlink/common/mavlink_msg_sys_status.h \
    Mavlink/common/mavlink_msg_system_time.h \
    Mavlink/common/mavlink_msg_terrain_check.h \
    Mavlink/common/mavlink_msg_terrain_data.h \
    Mavlink/common/mavlink_msg_terrain_report.h \
    Mavlink/common/mavlink_msg_terrain_request.h \
    Mavlink/common/mavlink_msg_timesync.h \
    Mavlink/common/mavlink_msg_v2_extension.h \
    Mavlink/common/mavlink_msg_vfr_hud.h \
    Mavlink/common/mavlink_msg_vibration.h \
    Mavlink/common/mavlink_msg_vicon_position_estimate.h \
    Mavlink/common/mavlink_msg_vision_position_estimate.h \
    Mavlink/common/mavlink_msg_vision_speed_estimate.h \
    Mavlink/common/mavlink_msg_wind_cov.h \
    Mavlink/common/testsuite.h \
    Mavlink/common/version.h \
    Mavlink/matrixpilot/matrixpilot.h \
    Mavlink/matrixpilot/mavlink.h \
    Mavlink/matrixpilot/mavlink_msg_airspeeds.h \
    Mavlink/matrixpilot/mavlink_msg_altitudes.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_command.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_directory.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    Mavlink/matrixpilot/mavlink_msg_flexifunction_set.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    Mavlink/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    Mavlink/matrixpilot/testsuite.h \
    Mavlink/matrixpilot/version.h \
    Mavlink/minimal/mavlink.h \
    Mavlink/minimal/mavlink_msg_heartbeat.h \
    Mavlink/minimal/minimal.h \
    Mavlink/minimal/testsuite.h \
    Mavlink/minimal/version.h \
    Mavlink/slugs/mavlink.h \
    Mavlink/slugs/mavlink_msg_boot.h \
    Mavlink/slugs/mavlink_msg_control_surface.h \
    Mavlink/slugs/mavlink_msg_cpu_load.h \
    Mavlink/slugs/mavlink_msg_ctrl_srfc_pt.h \
    Mavlink/slugs/mavlink_msg_data_log.h \
    Mavlink/slugs/mavlink_msg_diagnostic.h \
    Mavlink/slugs/mavlink_msg_gps_date_time.h \
    Mavlink/slugs/mavlink_msg_isr_location.h \
    Mavlink/slugs/mavlink_msg_mid_lvl_cmds.h \
    Mavlink/slugs/mavlink_msg_novatel_diag.h \
    Mavlink/slugs/mavlink_msg_ptz_status.h \
    Mavlink/slugs/mavlink_msg_sensor_bias.h \
    Mavlink/slugs/mavlink_msg_sensor_diag.h \
    Mavlink/slugs/mavlink_msg_slugs_camera_order.h \
    Mavlink/slugs/mavlink_msg_slugs_configuration_camera.h \
    Mavlink/slugs/mavlink_msg_slugs_mobile_location.h \
    Mavlink/slugs/mavlink_msg_slugs_navigation.h \
    Mavlink/slugs/mavlink_msg_status_gps.h \
    Mavlink/slugs/mavlink_msg_uav_status.h \
    Mavlink/slugs/mavlink_msg_volt_sensor.h \
    Mavlink/slugs/slugs.h \
    Mavlink/slugs/testsuite.h \
    Mavlink/slugs/version.h \
    Mavlink/test/mavlink.h \
    Mavlink/test/mavlink_msg_test_types.h \
    Mavlink/test/test.h \
    Mavlink/test/testsuite.h \
    Mavlink/test/version.h \
    Mavlink/uAvionix/mavlink.h \
    Mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    Mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    Mavlink/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    Mavlink/uAvionix/testsuite.h \
    Mavlink/uAvionix/uAvionix.h \
    Mavlink/uAvionix/version.h \
    Mavlink/checksum.h \
    Mavlink/mavlink_conversions.h \
    Mavlink/mavlink_get_info.h \
    Mavlink/mavlink_helpers.h \
    Mavlink/mavlink_sha256.h \
    Mavlink/mavlink_types.h \
    Mavlink/protocol.h \
    modules/uas_message/uas_message_tcp_framer.hpp \
    modules/goose_census/goose_census.hpp \





FORMS    += gcomcontroller.ui

INCLUDEPATH += Mavlink

CONFIG += c++14

RESOURCES = resources.qrc
