# Generated by Django 5.1.14 on 2025-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronetelemetry',
            name='timestamp',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
