# Generated by Django 5.1.13 on 2025-11-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drone", "0002_alter_dronetelemetry_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="dronetelemetry",
            name="armed",
            field=models.BooleanField(default=False),
        ),
    ]
