services:
  python-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
      - ./pyproject.toml:/src/pyproject.toml
    environment:
      - PYTHONPATH=/src
      - PATH=/root/.local/bin:$PATH
    ports:
      - "8000:8000"
