# Generated by Django 5.1.13 on 2025-11-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nav", "0003_remove_waypoint_route_orderedwaypoint_route"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderedwaypoint",
            options={"ordering": ["order"]},
        ),
        migrations.AlterUniqueTogether(
            name="orderedwaypoint",
            unique_together={("route", "order")},
        ),
    ]
