# Generated by Django 5.1.13 on 2025-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nav", "0003_remove_waypoint_route_orderedwaypoint_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypoint",
            name="ardupilot_param2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="ardupilot_param3",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
