# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    #TODO delete go-workflow once merged with master
    branches: [ "master", "go-workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Build
      run: go build 
      
    - name: check modules
      run: |
        go mod verify
        go mod tidy

#We cannot run go test because the mp_test.go file requires a connection with mission planner which this workflow cannot support.
#Instead we must run each test manually
    - name: Test
    # run: go test 
      run: | 
        go test controllers_test.go controllers.go
        # go test -run "^db_test.go$"
        # go test -run "^pathfinding_test.go$"
        # go test -run "^odlc_test.go$"
        # go test -run "^rcomms_test.go$"
    
    
      
